export const skillProjectData = {
  skills: [
    { id: "java", name: "Java", projectIds: ["e5"] },
    {
      id: "python",
      name: "Python",
      projectIds: ["e1", "e2", "e3", "e4", "p2", "p6", "p7"],
    },
    { id: "mips", name: "MIPS Assembly", projectIds: ["p4"] },
    {
      id: "bash",
      name: "Shell Bash",
      projectIds: ["e1", "e2", "e3", "e4", "p1", "p2", "p3", "p5", "p6", "p7"],
    },
    { id: "go", name: "Go", projectIds: ["e1"] },
    { id: "fortran", name: "Fortran", projectIds: ["e2"] },
    {
      id: "js",
      name: "JavaScript",
      projectIds: ["p1", "p2", "p3", "p5", "p7"],
    },
    { id: "css", name: "CSS", projectIds: ["p1", "p2", "p3", "p5", "p7"] },
    { id: "ts", name: "TypeScript", projectIds: ["p1", "p3", "p5"] },
    { id: "html", name: "HTML", projectIds: ["p1", "p2", "p3", "p5", "p7"] },
    { id: "sql", name: "SQL", projectIds: ["e1", "p2"] },
    { id: "latex", name: "LaTex", projectIds: ["e2", "e3"] },
    {
      id: "react",
      name: "React.js",
      projectIds: ["p1", "p2", "p3", "p5", "p7"],
    },
    { id: "node", name: "Node.js", projectIds: ["p5"] },
    { id: "express", name: "Express.js", projectIds: ["p5"] },
    { id: "flask", name: "Flask", projectIds: ["p2"] },
    { id: "mango", name: "MangoDB", projectIds: ["p5"] },
    { id: "pg", name: "PostgresDB", projectIds: ["e1", "p2"] },
    { id: "velocity", name: "Apache Velocity", projectIds: ["e5"] },
    { id: "jupyter", name: "Jupyter Notebook", projectIds: ["e3", "p6", "p7"] },
    { id: "pandas", name: "Pandas", projectIds: ["e2", "e3", "p6", "p7"] },
    { id: "numpy", name: "NumPy", projectIds: ["e2", "e3", "p6", "p7"] },
    { id: "matplotlib", name: "MatPlotLib", projectIds: ["e2", "e3", "p7"] },
    { id: "sci", name: "Scikit Learn", projectIds: ["e3", "p6", "p7"] },
    { id: "cv", name: "OpenCV", projectIds: ["p6"] },
    { id: "k8s", name: "Kubernetes", projectIds: ["e1"] },
    { id: "argo", name: "ArgoCD", projectIds: ["e1"] },
    { id: "aws", name: "Amazon Web Services", projectIds: ["e1", "p1"] },
    { id: "tf", name: "Terraform", projectIds: ["e1", "p1"] },
    { id: "jenkins", name: "Jenkins", projectIds: ["e1"] },
    {
      id: "docker",
      name: "Docker",
      projectIds: ["e1", "p1", "p2", "p3", "p5", "p7"],
    },
    { id: "aurora", name: "Aurora/Mesos", projectIds: ["e1"] },
    { id: "grafana", name: "Grafana", projectIds: ["e1"] },
    { id: "prom", name: "Prometheus", projectIds: ["e1"] },
    { id: "loki", name: "Loki", projectIds: ["e1"] },
    { id: "figma", name: "Figma", projectIds: ["e3", "p1", "p2", "p5", "p7"] },
    { id: "vsm", name: "VSM", projectIds: ["e2"] },
    { id: "afm", name: "AFM", projectIds: ["e2"] },
    { id: "sputter", name: "Sputtering Machine", projectIds: ["e2"] },
    { id: "mfm", name: "MFM", projectIds: ["e2"] },
    { id: "moke", name: "MOKE", projectIds: ["e2"] },
  ],
  experiences: [
    {
      id: "e1",
      name: "Medallia",
      skillIds: [
        "pg",
        "aws",
        "python",
        "go",
        "k8s",
        "argo",
        "jenkins",
        "aurora",
        "bash",
        "grafana",
        "prom",
        "loki",
        "tf",
        "docker",
        "sql",
      ],
      description:
        "I executed over 200 service deployments and updates, maintaining FEDRAMP-high security protocols in the AWS GovCloud environment. I developed an SSL certificate manager to streamline certificate replacements within the Kubernetes environment and ensured 24/7 service availability through on-call rotations and collaboration with application teams. Additionally, I efficiently migrated services from Aurora/Mesos to Kubernetes, used Grafana and Loki to create monitoring dashboards, and pinpoint error logs across the GovCloud environment. I also designed architecture diagrams to support significant changes to the environment.",
      images: ["/images/medallia.png", "/images/medallia2.webp"],
      date: "Summer 2024 - Present",
      links: ["https://www.medallia.com"],
      title: "Site Reliability Engineer",
    },
    {
      id: "e2",
      name: "Integrated Nano Computing Lab",
      skillIds: [
        "python",
        "fortran",
        "bash",
        "pandas",
        "numpy",
        "matplotlib",
        "vsm",
        "latex",
        "afm",
        "sputter",
        "mfm",
        "moke",
      ],
      description: "I led the growth of skyrmion stacks using a sputtering machine and characterized them with VSM and MFM, while utilizing MOKE imaging to visualize the skyrmions. Additionally, I refined simulations of magnetic tunnel junction-based true random number generators by incorporating both adiabatic and non-adiabatic torques. I also developed and verified a simulation for antiferromagnetic tunnel junction-based true random number generators, showcasing their potential for superfast switching and low-power operation.",
      images: ["/images/INC-Logo.png", "/images/incphoto.jpeg"],
      date: "Fall 2024 - Present",
      links: ["https://utinclab.com/"],
      title: "Research Assistant",
    },
    {
      id: "e3",
      name: "Neuro Spin Compute Laboratory",
      skillIds: [
        "python",
        "bash",
        "pandas",
        "numpy",
        "matplotlib",
        "jupyter",
        "latex",
        "figma",
        "sci",
      ],
      description: "I investigated hybrid logic locking systems utilizing strain-modulated nanomagnets under Dr. Joseph S. Friedman, where I led the development of logic-locking programs through innovative applications of graph partitioning algorithms. I encrypted over 500,000 different netlists and ran them through a satisfiability solver simulation, quantifying algorithmic security and improving encryption times from 2 seconds to over 12 hours. Additionally, as a Research Assistant at the Center for Robust Speech Systems, I collaborated with NASA to analyze Human Exploration Research Analog audio recordings under Dr. John H. L. Hansen. I optimized speech audio detection inferences for more than 16 hours of audio using the open-source ESPnet framework, analyzing word error rates and signal-to-noise ratios for different audio devices with the Whisper automatic speech recognition model.",
      images: ["/images/nsclogo.png", "/images/nsc.jpg"],
      date: "Summer 2022 - Spring 2024",
      links: ["https://personal.utdallas.edu/~joseph.friedman/"],
      title: "Research Assistant",
    },
    {
      id: "e4",
      name: "Center for Robust Speech Systems",
      skillIds: ["python", "bash"],
      description: "",
      images: [],
      date: "Fall 2023 - Spring 2024",
      links: ["https://crss.utdallas.edu/"],
      title: "Research Assistant",
    },
    {
      id: "e5",
      name: "Collins Aerospace",
      skillIds: ["java", "velocity"],
      description: "",
      images: [],
      date: "Summer 2023",
      links: ["https://www.collinsaerospace.com/"],
      title: "Software Engineer Intern",
    },
  ],
  projects: [
    {
      id: "p1",
      name: "FiscalFootprint: Government Spending Visualizer",
      skillIds: [
        "react",
        "bash",
        "js",
        "html",
        "css",
        "ts",
        "tf",
        "aws",
        "figma",
        "docker",
      ],
      description: "",
      images: [],
      date: "Fall 2024",
      links: ["https://github.com/rohanchugh14/hacktx2024"],
      title: "",
    },
    {
      id: "p3",
      name: "Briar Ziggs: Gamer Personality Test",
      skillIds: ["react", "bash", "js", "html", "css", "ts", "docker"],
      description: "",
      images: [],
      date: "Summer 2024",
      links: ["https://github.com/Alexander-N-Chin/Briar-Ziggs", "https://briarziggs.com/"],
      title: "",
    },
    {
      id: "p2",
      name: "PolyphonyPal: Sheet Music Generator",
      skillIds: [
        "python",
        "react",
        "bash",
        "js",
        "html",
        "css",
        "flask",
        "sql",
        "pg",
        "docker",
        "figma",
      ],
      description: "",
      images: [],
      date: "Spring 2024",
      links: ["https://github.com/PolyphonyPal-HQ/polyphony-pal", "https://polyphonypal.netlify.app/"],
      title: "",
    },
    {
      id: "p5",
      name: "Ready Player Credit: Gamify Financial Literacy",
      skillIds: [
        "react",
        "bash",
        "js",
        "html",
        "css",
        "ts",
        "docker",
        "express",
        "node",
        "mango",
        "figma",
      ],
      description: "",
      images: [],
      date: "Spring 2023",
      links: ["https://github.com/rohanchugh14/gamify-credit-cards", "https://readyplayercredit.netlify.app/"],
      title: "",
    },
    {
      id: "p6",
      name: "ErgoBlink: Posture and Blink Detection",
      skillIds: ["python", "bash", "jupyter", "numpy", "pandas", "sci", "cv"],
      description: "",
      images: [],
      date: "Spring 2023",
      links: ["https://github.com/Alexander-N-Chin/ErgoBlink"],
      title: "",
    },
    {
      id: "p4",
      name: "Sorting Visualizer",
      skillIds: ["mips"],
      description: "",
      images: [],
      date: "Spring 2022",
      links: ["https://github.com/Alexander-N-Chin/Sorting-Visualizer"],
      title: "",
    },
    {
      id: "p7",
      name: "ResuBot: Resume Grader",
      skillIds: [
        "js",
        "css",
        "html",
        "react",
        "python",
        "bash",
        "jupyter",
        "numpy",
        "pandas",
        "sci",
        "matplotlib",
        "docker",
        "figma",
      ],
      description: "",
      images: ["/images/resubot.png", "/images/resubot2.png"],
      date: "Fall 2022",
      links: [
        "https://github.com/UTD-AIS-Mentorship/Resume-Grading-and-Job-Recommendation-Fall-22",
        "https://www.youtube.com/live/HAyAWdbnM7g?feature=share&t=2369",
      ],
      title: "",
    },
  ],
};
